# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-06 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hospital', max_length=100, null=True)),
                ('capacity', models.IntegerField(default=100)),
                ('currentPatients', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('dosage', models.CharField(default='Dosage', max_length=7)),
                ('given', models.DateField(default=datetime.date.today)),
                ('expire', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('result', models.CharField(default='Result', max_length=100)),
                ('release', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='medical',
            name='prescriptions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Prescription'),
        ),
        migrations.AddField(
            model_name='medical',
            name='tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Test'),
        ),
    ]
